/** @format */

declare module "akaneko";
declare module "go-image-go";
declare module "mathjs";
declare module "canvacord";
declare module "genshin-db";
declare module "shentai";
declare module "mywaifulist-scraper";
declare module "mal-scraper";
declare module "wikipedia";
declare module "anime-wallpaper";
declare module "translate-google";
declare module "animequotes";
declare module "node-periodic-table";
declare module "oakdex-pokedex";
declare module "ptable";
declare module "node-myanimelist";
declare module "genius-lyrics";
declare module "trace.moe.ts";
declare module "anilist-node";
declare module "pokedex-promise-v2";
declare module "imgbb-uploader";
declare module "emoji-api";
declare module "vtuber-wiki";
declare module "node-myanimelist";
declare module "discord-image-generation";
declare module "discord-canvas";
declare module "ordinal";
